In [4]:
# sc.install_pypi_package("boto3")
import boto3
import sys
import time
import re
from botocore.client import Config
from datetime import datetime
pattern='ID_adapundi|ID_credinex|dumarket'
import uuid
client = boto3.client('quicksight',region_name='ap-southeast-1')
athena = boto3.client('athena',region_name='ap-southeast-1')
s3=boto3.client('s3')
dynamodb=boto3.client('dynamodb',region_name='ap-southeast-1')
datasetList =[{'ID_adapundi_marketing_auto_task_total': {'DataSetId': '01347efb-eee0-4fcf-bb53-b47aacf83c7c'}}, {'ID_ada_collection_V-1': {'DataSetId': '02c90f3e-d17c-4cfe-b06b-4da4cb19371a'}}, {'Sales Pipeline': {'DataSetId': '030e341c-6a0a-4e15-be96-97d2a38c2652'}}, {'ID_adapundi_operation_payday_retention_rate_by_times': {'DataSetId': '038e563e-2e92-44a4-baf2-7580e3cb5efc'}}, {'dumarket_dd_siteid_summary': {'DataSetId': '03f7cb43-dee3-41d3-80cc-2a37ca0fe219'}}, {'ID_adapundi_finance_profit_by_month': {'DataSetId': '04e35223-1a68-4e6e-b0c3-d3e10dc85fb4'}}, {'ID_adapundi_marketing_auto_task_new_contrast': {'DataSetId': '054a17c6-dcb6-4c6a-b9dc-47f652f276b1'}}, {'ID_adapundi_product_old_behavior_report': {'DataSetId': '060e21ea-4e84-48be-9783-90278b0730b7'}}, {'ID_adapundi_thirdpartyhit_izi_tycm_blacklist': {'DataSetId': '06929685-2a9a-4fd6-93e4-f0e7988f6733'}}, {'ID_adapundi_risk_level_conversion_new': {'DataSetId': '079d7f9e-4652-405c-92cc-f227ba1553fc'}}, {'ID_adapundi_automated_marketing_V3.0_old_huoe_not_tixian': {'DataSetId': '07e2b447-1a53-4ab7-9c64-60a53b552207'}}, {'ID_adapundi_tele_today': {'DataSetId': '0ab98bf3-842b-470d-bd7f-74d5b724cdd2'}}, {'credinex-风控规则拒贷': {'DataSetId': '0c042d7a-762d-44e0-af67-e1dcd2991332'}}, {'dumarket_total_summary': {'DataSetId': '0e1da4be-1836-425c-9904-179855251854'}}, {'ID_adapundi_thirdpartyhit_cost_Indonesia_Time': {'DataSetId': '0eeb4a18-7f98-4630-90a5-36bf3154ebdc'}}, {'ID_dumarket_finance_ adakami_expense': {'DataSetId': '0ef307f7-a8df-436c-9d42-8707a6c007b4'}}, {'ID_credinex_risk_transrate_report': {'DataSetId': '10210120-2b43-4d9b-82b5-c5c63e1d33f8'}}, {'ID_ada_collection_V-3': {'DataSetId': '1037f1c6-d5a0-4817-b473-33d70a581d9a'}}, {'ID_adapundi_tele_daily': {'DataSetId': '129e54cb-3d34-41a9-a3c1-df09b51012d7'}}, {'credinex-人审审核': {'DataSetId': '1557641f-2d79-4b87-a5b5-ea642ac92d42'}}, {'ID_adapundi_marketing_auto_task_old_contrast': {'DataSetId': '178dbfa5-5c20-4417-9094-318fa8d29967'}}, {'ID_adapundi_thirdpartyhit_advance_multiplatform': {'DataSetId': '183ef504-2911-4fea-b1f3-e2cb8831ed92'}}, {'ID_dumarket_finance_bankcard_verify': {'DataSetId': '184e2941-c42c-42ab-b36a-c084db8b0dab'}}, {'ID_ada_collection_monthly_paid_rate': {'DataSetId': '18ecd14a-7561-442f-916e-57e4771385f4'}}, {'ID_adapundi_real-time_payday_review_level_conversion_register': {'DataSetId': '196a2ebc-6b57-40bc-90ac-b2ed04282ddc'}}, {'credinex-风控层级转化': {'DataSetId': '1c29e990-497c-4b2c-a3e2-e03a85cd3afc'}}, {'ID_adapundi_marketing_coupon_use_weekly': {'DataSetId': '1c3ab4bc-be92-4b53-8d98-2a4e230bed9a'}}, {'ID_adapundi_product_daily_behavior_report': {'DataSetId': '1c8ce781-6280-40bc-a5bd-d4de8eb3f820'}}, {'ID_adapundi_real-time_monitor_old_conversion': {'DataSetId': '1d41db6f-fd2e-40f8-b137-a4cf1647fc06'}}, {'ID_dumarket_finance_DokterDana_profit_by_month': {'DataSetId': '1e228d7e-3d0e-48b5-9004-74c794eaa6bf'}}, {'ID_adapundi_marketing_daily_basic_with_cost': {'DataSetId': '1eae084a-7b8f-48cd-9d86-5df11f177df9'}}, {'ID_adapundi_automated_marketing_V3.0_huoe_new': {'DataSetId': '1fe6145a-171b-4c3a-a32b-d26476c37a56'}}, {'ID_adapundi_operation_payday_monthly_retention_rate': {'DataSetId': '20b33e0d-3270-49cc-96ad-a4829cf571ca'}}, {'ID_adapundi_automated_marketing_V3.0_new_register_not_record': {'DataSetId': '21553953-6092-4f18-839f-ccbcd99d48d7'}}, {'dumarket_dd_total_summary': {'DataSetId': '223b8037-448a-4e91-9935-f10de71c5d43'}}, {'ID_adapundi_real-time_competitor': {'DataSetId': '2517bfe0-d87a-42ca-bc98-4bc3fd129237'}}, {'ID_adapundi_collection_default_fee_paid': {'DataSetId': '259821e0-96dc-4982-a9e6-f6fe91dd7cfd'}}, {'ID_adapundi_thirdpartyhit_pay': {'DataSetId': '26f79416-ebae-4bdb-ac4d-21bb28c80f97'}}, {'ID_adapundi_collection_monthly_default_paid': {'DataSetId': '279e26f1-103a-4019-bdf0-ab7dd9f06c49'}}, {'ID_adapundi_finance_loan_banlace_today': {'DataSetId': '2933316e-83e5-44c4-9b2b-8f124fcc89be'}}, {'ID_credinex_loan_review_loan_review_efficiency': {'DataSetId': '295a1086-2b22-497b-adff-e4ca984cde33'}}, {'ID_adapundi_collection_PAYDAY_Vintage_rate': {'DataSetId': '2a9e1789-c360-46e4-b5d3-d85296d7d4d2'}}, {'ID_adapundi_product_daily_rollover_data_issue_basis': {'DataSetId': '2ae232ad-6a18-42ee-bcc5-922ecb82d126'}}, {'Web and Social Media Analytics': {'DataSetId': '2b96a365-14d6-4a95-864b-ecfb987b42b6'}}, {'happycash_daily_new_loan': {'DataSetId': '2cb5ab90-5745-4723-8204-f935070aa7ff'}}, {'ID_credinex_operation_daily_platform_summary_install': {'DataSetId': '2d699525-fafb-458a-bde8-248608c7c312'}}, {'ID_adapundi_thirdpartyhit_issue': {'DataSetId': '2e4ba1b0-b297-4c96-b765-b6af744730c3'}}, {'sql_test': {'DataSetId': '2e6c8286-b0ac-4a83-85a1-22f211b93e7e'}}, {'Web and Social Media Analytics': {'DataSetId': '2f3f8d7b-d7c1-43d0-be2a-b3b23ce2400d'}}, {'ID_adapundi_daily_platform_daily_summary': {'DataSetId': '30937b1b-4f47-45c5-85bb-b102b12945c9'}}, {'ID_adapundi_real-time_old_distribution': {'DataSetId': '30c3ef59-d0bf-47b6-b601-931ad0b79906'}}, {'Happycash general overdue analysis after 2020-03-17': {'DataSetId': '34008a01-8eaf-4f86-9bc8-593269ebe9cb'}}, {'ID_adapundi_finance_daily_USD_loans_revenue': {'DataSetId': '34bc31c3-00a3-4172-b992-f1deb1c5a06b'}}, {'ID_adapundi_telemarketing_today': {'DataSetId': '35e83a47-20f6-4fe9-930d-7cdc8279a481'}}, {'ID_adapundi_marketing_register_basic': {'DataSetId': '362794c3-5997-4338-9e86-4483616078d2'}}, {'ID_credinex_loan_review_loan_review_not_deal': {'DataSetId': '3c8e238e-49f6-4512-897d-b4cfdff2e4c1'}}, {'ID_adapundi_marketing_auto_task_new': {'DataSetId': '3ecb9370-48c4-4e51-a122-0a19916f7314'}}, {'ID_adapundi_risk_monthly_amount_overdue': {'DataSetId': '3edaab56-f2ff-4fdf-9ded-a358f546d707'}}, {'ID_ada_coll._PAYDAY_VINTAGE': {'DataSetId': '427c3284-013d-4f11-8df4-2b8c09f6b569'}}, {'ID_credinex_operation_daily_register_apply': {'DataSetId': '431d749f-21a3-4478-ae60-4b2073310fea'}}, {'ID_credinex_risk_credit_detail_report': {'DataSetId': '44dc08da-e843-4bdb-8f56-9ee257246b89'}}, {'ID_adapundi_product_invitation_entrance': {'DataSetId': '45d34650-da42-4677-b896-2b1742b8018f'}}, {'ID_adapundi_product_user_behavior_report-register_basic': {'DataSetId': '4693fa21-d395-4725-ae11-6ecc0822f8cd'}}, {'ID_adapundi_real-time_tag': {'DataSetId': '478b2993-a236-4ddf-952c-c969e8423d8f'}}, {'ID_adapundi_real-time_indicator_monitoring': {'DataSetId': '488f69a4-f718-423b-952e-2d1c4c6ed9f9'}}, {'ID_adapundi_real-time_repay': {'DataSetId': '4aa27ae7-3846-44a7-b720-73d9d59d7285'}}, {'ID_credinex_risk_trans_report': {'DataSetId': '4ad60f12-283e-4f07-b168-e3b4e7945f2c'}}, {'dumarket_product_siteid_summary': {'DataSetId': '4b167018-23bf-4868-b3f2-11f29405c994'}}, {'ID_AdaPundi_OTP_monitoring_OTP_user_type': {'DataSetId': '4cd02121-b116-4b6c-9a67-8fa914953154'}}, {'People Overview': {'DataSetId': '4da68d8b-b51d-4575-94f6-e7b831830d45'}}, {'ID_adapundi_thirdpartyhit_cost_Chinese_Time': {'DataSetId': '5134baae-17ff-4f27-acd8-93d264439d66'}}, {'ID_adapundi_marketing_daily_basic_with_cost_channel_2': {'DataSetId': '51726605-24e5-42e1-86eb-fbaa29237240'}}, {'ID_adapundi_finance_loan_banlace-summary': {'DataSetId': '51c5aec9-b3a0-4383-b8ec-de67ec80eedf'}}, {'Adapundi event tracking daily health check': {'DataSetId': '51de3e6a-660f-439e-9326-73f31723646b'}}, {'happycash_loan_revenue_month': {'DataSetId': '5384adbd-4a3f-461f-ac9d-d0261972aced'}}, {'Business Review': {'DataSetId': '556e4b8f-9b4f-4db3-85e1-01d1914d985c'}}, {'ID_adapundi_marketing_tele_trigger': {'DataSetId': '55790d72-63ce-49d9-84de-36332ae6b21c'}}, {'ID_adapundi_daily_RPD_Authorized_to_Withdraw': {'DataSetId': '57fe8b99-f5dc-4f3f-a0ba-7b53f691d37a'}}, {'ID_adapundi_risk_daily_amount_overdue': {'DataSetId': '59015710-ff4e-4a53-9311-21da2861b55e'}}, {'dumarket_user_daily_report': {'DataSetId': '5b12bf51-7af4-438d-a05b-0ebbade46094'}}, {'dumarket_dd_total_summary_dompetdana': {'DataSetId': '5b4f2e3a-e1bc-446b-a0e9-2d740c1cb70b'}}, {'Sales Pipeline': {'DataSetId': '5b896372-bb41-4f98-ae08-52d0cc9c4266'}}, {'ID_Adapundi_finance_ONLINE': {'DataSetId': '5c508f48-d71b-4b93-9e5d-98d27a36a65f'}}, {'ID_ada_coll._rep_vintage(risk_amount)': {'DataSetId': '5d8c97c3-aa6e-4461-9189-fe6ef7ebab10'}}, {'Group 1': {'DataSetId': '5e9179e7-d44f-4bfa-933f-2ffaa9dcf7fc'}}, {'ID_dumarket_finance_blacklist': {'DataSetId': '5f22ca76-2a19-4394-9f5a-874e81bd1021'}}, {'dumarket_product_app_summary': {'DataSetId': '602fb18d-a68a-4f88-8a9b-705a67e64a4a'}}, {'happycash_reloan_week': {'DataSetId': '613f0b49-f3ed-414e-a125-83414d5968a3'}}, {'ID_AdaPundi_OTP_monitoring_withdraw_repayday': {'DataSetId': '62060d13-de4f-4a3d-a313-ef20c6e159fe'}}, {'ID_credinex_operation_daily_user_retention': {'DataSetId': '63500521-7aa4-4608-9464-5835432a1894'}}, {'ID_adapundi_automated_marketing_V3.0_whitelist_huoe_not_tixian': {'DataSetId': '639ce9db-936e-4959-9f20-b12e766dfa9e'}}, {'ID_adapundi_marketing_auto_task_old': {'DataSetId': '63b460c1-eca3-4f40-829a-781f162f465d'}}, {'ID_adapundi_thirdpartyhit_advance_blacklist': {'DataSetId': '642031e4-3009-4047-b470-8429f56246b3'}}, {'happycash_loan_revenue_daily': {'DataSetId': '64a7e891-6177-4737-8ee2-098eac583af5'}}, {'ID_adapundi_telemarketing_handler': {'DataSetId': '678d9e58-284a-49e0-b618-a8e3dfcb51e0'}}, {'新的自定义 SQL': {'DataSetId': '683c7d94-b8cf-44ab-a9fe-4e654098b2ef'}}, {'ID_adapundi_daily_platform_daily_summary_by_register': {'DataSetId': '68989a25-c8c4-44c6-99a8-b7edede11d76'}}, {'ID_adapundi_product_version-register_basic_by_day': {'DataSetId': '6a435e9f-fee1-48b4-849b-fedd44550b9e'}}, {'happycash_daily_overdue_situation': {'DataSetId': '6a9e14cb-0ef4-49c2-863d-05731d92925d'}}, {'Sales Pipeline': {'DataSetId': '6adad598-584a-4347-9c16-0d5e5a88d33f'}}, {'happycash_daily_finance': {'DataSetId': '6e6cd240-679c-4e11-a943-b91f8ed25887'}}, {'ID_adapundi_risk_weekly_amount_overdue': {'DataSetId': '716676fd-abbc-4264-ac69-db8095b49fe1'}}, {'ID_adapundi_marketing_coupon_use_monthly': {'DataSetId': '71b99980-a459-425e-a057-a9170dba9345'}}, {'ID_adapundi_product_invitation_behavior_report': {'DataSetId': '72099677-f58a-4794-a6d3-622794086a56'}}, {'ID_adapundi_real-time_old_customer': {'DataSetId': '72953de9-29c1-4d0a-8bbd-c7519181fd0f'}}, {'behavior_report_test1': {'DataSetId': '7491cbce-c645-40f5-b20b-0e9fae9fab6e'}}, {'ID_adapundi_product_product_conversation': {'DataSetId': '75b816bd-1d4e-4da6-ade9-701102c6f4d3'}}, {'ID_adapundi_daily_PD_Install_to_Register': {'DataSetId': '75d6593f-de0a-4b3b-a501-c445ff3961ba'}}, {'ID_ada_coll._re_payday_vintage(num>3)': {'DataSetId': '7685ed0a-b8c1-44bb-a099-108646fc35a5'}}, {'ID_adapundi_real-time_payday_review_level_conversion_apply': {'DataSetId': '76c099f3-36f3-4dac-a8d8-817f736f1839'}}, {'happycash_finance_daily_repay': {'DataSetId': '7770cab7-5560-4e78-8698-f178f3cc1013'}}, {'dumarket_dd_total_summary_new': {'DataSetId': '78f64061-bfa6-473f-9766-7e805e5637f2'}}, {'ID_adapundi_telemarketing_today_hour': {'DataSetId': '798a55ab-aa11-41ba-aaeb-357e9c383e05'}}, {'ID_adapundi_thirdpartyhit_10015_chinese': {'DataSetId': '7a7951c6-3ba3-49ce-b229-161aca36158b'}}, {'ID_credinex_finance_detail_consumption': {'DataSetId': '7b411d2e-bedf-4345-8c86-b50ebfdc5c48'}}, {'ID_adapundi_real-time_old_transfrom': {'DataSetId': '7ee3dbf0-eef4-4713-a6e4-aa1fc0f98e4b'}}, {'ID_adapundi_thirdpartyhit_10015_Indonesia': {'DataSetId': '7f8add6b-95ed-4853-81c4-54b78c91bbb1'}}, {'ID_ada_coll._monthly_V-1(risk_$)': {'DataSetId': '800666f2-22ef-4439-a09d-712844e4c5eb'}}, {'ID_credinex_loan_review_loan_review_details': {'DataSetId': '80f92b66-d164-4b95-adfe-c045aa6e26ed'}}, {'People Overview': {'DataSetId': '8162fffd-6606-486a-bce7-d52e59ae3675'}}, {'ID_credinex_marketing_H5_daily_basic': {'DataSetId': '850ed83c-9b60-44f0-806c-a514b46a6627'}}, {'ID_adapundi_product_user_behavior_report-daily_basic': {'DataSetId': '85feebff-1d4b-410f-9d1e-3f20765f3c4a'}}, {'happycash_reloan_daily': {'DataSetId': '86ba26b4-21d8-4e49-811a-fab87da3c87f'}}, {'ID_ada_coll._monthly_V-2(risk_$)': {'DataSetId': '87290102-0932-42d7-a960-0df1abf9702b'}}, {'ID_adapundi_real-time_recall': {'DataSetId': '879bd6dc-5b53-4d35-a5cd-d179054fe90d'}}, {'ID_ada_coll._monthly_V-1($)': {'DataSetId': '8a78842e-ae81-4b60-a854-62d350361d59'}}, {'ID_adapundi_product_version_user_behavior_report-register_basic_by_day': {'DataSetId': '8b5f5542-6034-4a1f-a4f6-8a75f499a039'}}, {'ID_credinex_finance_detail_repayment_BillsSummaryReport': {'DataSetId': '8baed284-b21f-4cdd-a997-284a8b355ff7'}}, {'ID_adapundi_product_daily_rollover_data_date_basis': {'DataSetId': '8bc42e26-c2b0-4723-824a-3d25be9e8de4'}}, {'ID_adapundi_product_invitation_weekly_report': {'DataSetId': '8e02aafb-c5c3-42f7-af6c-54bef58f6851'}}, {'ID_adapundi_automated_marketing_V3.0_huoe_whitelist': {'DataSetId': '8e8fbb79-4017-43a4-97b5-c3bfad5c0edd'}}, {'ID_adapundi_product_invitation_screen': {'DataSetId': '910b2b13-7ccb-47a9-aa38-bb7cbe02291a'}}, {'ID_adapundi_daily_platform_daily_pay': {'DataSetId': '912a9297-a54a-4c97-a045-b8b617d06adc'}}, {'ID_credinex_loan_review_loan_review_manual_overdue': {'DataSetId': '9132c4ef-5339-462b-872d-7c9463978d5e'}}, {'ID_credinex_marketing_daily_basic': {'DataSetId': '92086648-c989-467a-aa26-eed84c70d74a'}}, {'ID_AdaPundi_OTP_monitoring_OTP_channel': {'DataSetId': '93069616-9094-4a8f-8791-a5bf7a8d4d45'}}, {'ID_adapundi_thirdpartyhit_cost': {'DataSetId': '9552bcd5-76d8-4478-aa0f-ae98214e898f'}}, {'ID_adapundi_automated_marketing_V3.0_huoe_old': {'DataSetId': '97c2fc76-0002-4889-bae5-fcdb8abfcc35'}}, {'Business Review': {'DataSetId': '9a2d9676-704d-40ed-8e84-4bb008bb1221'}}, {'Web and Social Media Analytics': {'DataSetId': '9b43cf26-e48b-40f1-bf3c-096970030e0f'}}, {'dumarket_product_app_summary_dompetdana': {'DataSetId': '9c6e931d-78f4-41d2-a27e-c5c91cf45135'}}, {'ID_adapundi_risk_weekly_issue_overdue': {'DataSetId': '9c96e530-929b-4fe4-92ba-e8a01a3cd6b3'}}, {'ID_credinex_loan_review_loan_review_manual': {'DataSetId': '9d666d75-26ca-4c69-97b4-9feba9c7afa5'}}, {'ID_adapundi_product_user_login': {'DataSetId': '9de8030e-07f4-4631-af27-ce9a10048b86'}}, {'ID_credinex_risk_credit_summary_report': {'DataSetId': '9f329134-d148-4ce5-9e50-7f187c487829'}}, {'ID_adapundi_collection_monthly_totalpaid': {'DataSetId': 'a07e4805-87d3-46cb-a7ea-5bd43b97311a'}}, {'ID_ada_collection_re_payday_vintage': {'DataSetId': 'a0a9ec04-2ea1-49a8-aef1-ce5eeefdffc0'}}, {'ID_adapundi_real-time_monitor_new_conversion': {'DataSetId': 'a0ce93b7-b0af-4418-91dc-5031768f428f'}}, {'ID_adapundi_automated_marketing_V3.0_new_huoe_not_tixian': {'DataSetId': 'a18be081-a97b-4074-a8f1-c99a25a6debe'}}, {'ID_adapundi_collection_weekly_payday_vintage': {'DataSetId': 'a27b0452-b23f-4310-8051-a67da521e3d0'}}, {'ID_adapundi_tele_handler': {'DataSetId': 'a2c8a8dc-f398-46bc-834a-c6a9764c106e'}}, {'ID_adapundi_marketing_register_basic_with_cost_channel': {'DataSetId': 'a2cffd1d-519c-4cf6-b619-0c0e7805091e'}}, {'ID_ada_collcection_weekly_payday_vintage_rate': {'DataSetId': 'a3c603b8-7010-4b30-ae59-e162db2f867a'}}, {'ID_adapundi_thirdpartyhit_issue_and_pay_cost': {'DataSetId': 'a40cfe69-3c20-4b31-91a7-2f895dcb7301'}}, {'happycash_loan_revenue_week': {'DataSetId': 'a41985f8-c389-421b-99b8-2828e325ccf6'}}, {'ID_credinex_operation_daily_platform_summary_daily': {'DataSetId': 'a4431d4f-530a-4cbb-ac9f-5f09317633c2'}}, {'ID_ada_coll._re_payday_vintage(#)': {'DataSetId': 'a5faf614-40f0-4680-a844-e86674b6dda6'}}, {'ID_ada_coll._weekly8_payday(Risk)': {'DataSetId': 'a644dd85-1a4b-44cc-8365-25c2867e48f5'}}, {'ID_adapundi_daily_Paid_off_to_RPD_Apply': {'DataSetId': 'a6b813b0-9520-4cbf-8e13-af2b4207f8e7'}}, {'ID_credinex_marketing_register_basic': {'DataSetId': 'a7056694-50a6-468f-85b2-36c97dbbf336'}}, {'ID_adapundi_risk_monthly_issue_overdue': {'DataSetId': 'a72af21a-dbec-4531-9fb4-226e260c19aa'}}, {'ID_adapundi_finance_daily_USD_loans_revenue_repayday': {'DataSetId': 'a83c11f3-c37d-427b-9044-0970792e8ee4'}}, {'ID_AdaPundi_OTP_monitoring_OTP_conversion': {'DataSetId': 'aa300fb9-53b9-47b9-98e9-0f61a826434e'}}, {'ID_ada_collection_paid_rate_cp': {'DataSetId': 'ab3f0d22-f93f-46aa-bcc7-874bc64596fc'}}, {'ID_adapundi_real-time_payday_review': {'DataSetId': 'ac775f8e-1d2b-4247-b8ee-dd3f03c31826'}}, {'ID_credinex_operation_daily_active_to_transaction': {'DataSetId': 'ac7ff371-a56b-4ce8-8607-600f46745ea8'}}, {'ID_ada_collection_V1': {'DataSetId': 'ad5ebe9e-1d9f-49da-a1df-ff354a4195f4'}}, {'ID_adapundi_risk_level_conversion_whitelist': {'DataSetId': 'adcb0571-a59c-4e8d-9e38-46e210bb66cb'}}, {'ID_AdaPundi_OTP_monitoring_withdraw_payday': {'DataSetId': 'ae7dfeb9-5513-45e7-a32e-53e757dfc014'}}, {'ID_credinex_loan_review_loan_review_tele': {'DataSetId': 'af7e4000-4bd3-493c-aa37-404e62ca23fd'}}, {'ID_adapundi_product_user_behavior_report-register_basic_by_day': {'DataSetId': 'afba7d15-13f6-45f7-82ea-0636ad32ced8'}}, {'string': {'DataSetId': '1111'}}, {'AAAAAA': {'DataSetId': 'string'}}, {'ID_adapundi_telemarketing_handler_today': {'DataSetId': 'b252cb0e-e3e5-4b69-be0f-dac5b42c9db8'}}, {'ID_adapundi_risk_risk_conversation': {'DataSetId': 'b253e1c4-e372-433e-87f0-6793228f918e'}}, {'ID_adapundi_automated_marketing_V3.0_new_supplement': {'DataSetId': 'b4330926-aaf2-4aa5-a239-e44379336390'}}, {'ID_dumarket_finance_ whatsapp_expense': {'DataSetId': 'b584a573-98e8-4c50-be7e-66573b8988d0'}}, {'ID_credinex_finance_detail_repayment': {'DataSetId': 'b63ab557-5aa4-4351-ad99-bbac9277cf0a'}}, {'ID_adapundi_marketing_daily_basic_with_cost_channel': {'DataSetId': 'b79aee48-b42f-4b1a-96d6-988f216b6599'}}, {'ID_adapundi_thirdpartyhit_izi_brief_multiplatform': {'DataSetId': 'b7e36faf-c42e-4e57-a49d-ec5d8b479f63'}}, {'credinex-层级转化': {'DataSetId': 'b8367a13-907e-4722-8b4b-d53b6429104b'}}, {'People Overview': {'DataSetId': 'b91b7300-56d1-421a-9a2d-6a7c3fee9aca'}}, {'ID_ada_coll._monthly_V1(risk_$)': {'DataSetId': 'b97a89b8-7798-42b0-8ed2-8fc94942213a'}}, {'ID_adapundi_automated_marketing_V3.0_whitelist_firstlogin_not_loan': {'DataSetId': 'ba77950f-5c89-46fe-882d-8fade47ac01b'}}, {'ID_adapundi_finance_daily_USD_loans_revenue_payday': {'DataSetId': 'bab8b344-c4ff-49f2-b8a8-e43d03d19ee2'}}, {'ID_adapundi_product_rollover_data_rollover_date': {'DataSetId': 'bc55fb7e-bc0a-4621-a4e3-7912507ce7fe'}}, {'ID_credinex_operation_daily_transaction': {'DataSetId': 'be989ceb-45f1-4142-8cf5-6435e74c6ef8'}}, {'Business Review': {'DataSetId': 'beb99a9f-e8dd-4497-93aa-803ef72c3955'}}, {'ID_dumarket_Daily_Rejected_first_report': {'DataSetId': 'bfb2a172-a8e3-4bc3-b915-ee15eec82f5c'}}, {'ID_ada_coll._monthly_V-2$)': {'DataSetId': 'c0c6d81f-55bb-42f4-9a5d-0e4fd59d1716'}}, {'ID_adapundi_product_user_login_new': {'DataSetId': 'c0e3f0e0-0e28-40ae-a9e7-738c52b1be15'}}, {'ID_adapundi_collection_monthly_vintage1_rate': {'DataSetId': 'c1883122-140e-4fe0-9940-b319e0b24b78'}}, {'Adapundi event tracking health check for last month': {'DataSetId': 'c18a274d-b46e-4589-bc96-a786e42d698b'}}, {'ID_adapundi_daily_PD_Register_to_Apply': {'DataSetId': 'c1b89810-6d0c-4518-8a5a-5b808a843876'}}, {'ID_adapundi_telemarketing_code_conversion': {'DataSetId': 'c1e914a2-9904-45f3-b634-8e509a043921'}}, {'code detail': {'DataSetId': 'c44821c5-c704-4377-9ead-2ac57d9e807d'}}, {'Happy check daily check event tracking': {'DataSetId': 'c5b8bd39-3886-4e79-9921-6c5d4cb6aad4'}}, {'ID_adapundi_automated_marketing_V3.0_old_payoff_not_repayday': {'DataSetId': 'c7a3bcee-3fb3-4e5c-8005-708461de7f86'}}, {'happycash_finance_principle0317': {'DataSetId': 'cea2822a-3e96-4dd3-bd6d-fd99503e3de2'}}, {'ID_dumarket_Daily_Rejected_install': {'DataSetId': 'cf1d88aa-7354-4bdd-a178-2ff09bc941b2'}}, {'dumarket_product_app_summary_new': {'DataSetId': 'cfdb3136-7a79-43b1-9fad-879de5099a72'}}, {'ID_adapundi_daily_PD_Authorized_to_Withdraw': {'DataSetId': 'd0d1079c-f4b0-47b9-8ffd-3b1eac230eee'}}, {'happycash_app_behavior': {'DataSetId': 'd13aceab-7ec2-47a2-883e-2d998838d5fd'}}, {'ID_adapundi_marketing_daily_basic': {'DataSetId': 'd1d22c87-8641-4d3c-804c-a8243acbefd3'}}, {'ID_adapundi_automated_marketing_V3.0_new_payoff_not_repayday': {'DataSetId': 'd4eddcdc-8901-40f6-bdbc-94c54181d78f'}}, {'ID_adapundi_automated_marketing_V3.0_whitelist_payoff_not_repayday': {'DataSetId': 'd5b74d91-1283-4f5a-9263-3c29a8d3051c'}}, {'ID_adapundi_product_invitation_summary_report': {'DataSetId': 'd5e441df-baa7-4ced-a501-e7a40d62b3f7'}}, {'happycash_daily_old_new_loan': {'DataSetId': 'd625f14f-f853-4353-8268-202524cb0608'}}, {'ID_adapundi_product_invitation_daily_report': {'DataSetId': 'd6678eab-290a-4838-b1bf-a45496fcb5f8'}}, {'Sales Pipeline': {'DataSetId': 'd68d5cf8-6921-4160-bfbd-f42b81def418'}}, {'ID_credinex_marketing_H5_register_basic': {'DataSetId': 'd6b09533-2024-46eb-8bdb-4212a26ccb45'}}, {'ID_ada_coll._monthly_V1($)': {'DataSetId': 'd6f7df6f-43ca-41fe-8493-31b26497db0d'}}, {'ID_adapundi_thirdpartyhit_hadz_blacklist': {'DataSetId': 'd87367af-0a0d-47e9-a110-1b96d9a67819'}}, {'ID_adapundi_thirdpartyhit_izi_blacklist': {'DataSetId': 'db0c3d48-97bb-4746-9032-2fbc6a79350c'}}, {'ID_adapundi_product_rollover_data_due_date': {'DataSetId': 'dbb5197d-7c1a-4bfe-9987-839b8a5cec1f'}}, {'ID_adapundi_automated_marketing_V3.0_new_record_not_apply': {'DataSetId': 'dc09f4b0-e916-4434-834d-507c1f20f3b3'}}, {'ID_dumarket_finance_sms_situation': {'DataSetId': 'dcec66cb-f36f-4bf0-ac68-e9db34a96dd8'}}, {'ID_adapundi_telemarketing_conversion': {'DataSetId': 'de783f1f-6ed6-44db-b43c-37ef6ec3756d'}}, {'ID_adapundi_marketing_coupon_use_daily': {'DataSetId': 'de806861-8b86-4d91-b219-651988e01c18'}}, {'happycash_daily_overdue': {'DataSetId': 'e0b280a7-47c3-4d11-bcd0-4602de69c65a'}}, {'ID_AdaPundi_OTP_monitoring_OTP_install_send_btn': {'DataSetId': 'e1769136-74b7-409b-867c-5570f0554e52'}}, {'Web and Social Media Analytics': {'DataSetId': 'e2430cb8-e7bd-4c1a-9713-77c014a09a54'}}, {'ID_adapundi_marketing_total_by_month': {'DataSetId': 'e25cebc5-62d5-44bf-9ab2-f5ce12968129'}}, {'ID_ada_coll._rep_vintage(num>3_risk_amount)': {'DataSetId': 'e26561c5-ba52-4f75-8a3c-7f87d907dde7'}}, {'happycash_channel_evolve_date': {'DataSetId': 'e3fe49e8-6f42-490f-83b1-96bbeb1be3ff'}}, {'HappyCash event tracking health check for last month': {'DataSetId': 'e43817e3-6b33-4285-a498-ffbda1661ccc'}}, {'ID_adapundi_real-time_monitor_install_register': {'DataSetId': 'e44d83db-392d-4305-8f82-a19671ebaa08'}}, {'ID_ada_coll._pd_vintage(risk_amount)': {'DataSetId': 'e5b7199d-3901-469d-b21f-7d82a78ec7e8'}}, {'ID_credinex_operation_daily_active': {'DataSetId': 'e6012725-fea1-4271-9382-fe3c849b056a'}}, {'dumarket_dd_total_summary_dompetdana_new': {'DataSetId': 'e61b1bb3-9306-41aa-b780-29f9de8e1104'}}, {'ID_adapundi_product_new_behavior_report': {'DataSetId': 'e80380c9-52d7-4546-adcf-c58226d41ede'}}, {'ID_adapundi_finance_weekly_USD_loans_revenue': {'DataSetId': 'e9e08be6-cc8d-40c5-91ce-bcc3e55768bc'}}, {'ID_adapundi_finance_loans_revenue_simplified': {'DataSetId': 'ea564b31-f787-4bdd-a943-03cb87425b7a'}}, {'ID_adapundi_product_version-register_basic': {'DataSetId': 'eab85397-ea1d-411f-947f-155268f637d0'}}, {'ID_adapundi_real-time_monitor_core_product': {'DataSetId': 'ebf79953-0cd7-4db4-8ec0-e182288c81f1'}}, {'ETL_test': {'DataSetId': 'ec480fcc-8d48-4af3-95bd-273dbeeaa8dc'}}, {'ID_credinex_loan_review_loan_review_tele_overdue': {'DataSetId': 'ecfeda82-4bca-4f9f-9104-10decf4f59f6'}}, {'happycash_finance_loan_balance': {'DataSetId': 'ed0af9c0-c9f5-4209-a027-9d15aa0db0e2'}}, {'ID_adapundi_finance_loans_revenue_simplified_payday': {'DataSetId': 'ee59c710-7dde-42e0-a3c0-b75c15d2527c'}}, {'Happycash event track activity for last week': {'DataSetId': 'ee9ddb54-eef8-49b2-83f2-0a8da3e21633'}}, {'ID_adapundi_risk_daily_issue_overdue': {'DataSetId': 'ef2a1078-0dc2-4f60-aea9-6778d01bfec2'}}, {'People Overview': {'DataSetId': 'efb95efa-b365-4a4d-9a0f-38594ec5c296'}}, {'ID_AdaPundi_OTP_monitoring_OTP_numbers_of_sends': {'DataSetId': 'efeff698-e9d0-4082-a017-f5191a1f2f58'}}, {'happycash_reloan_month': {'DataSetId': 'f0b0990f-5497-4321-928a-1a8ec5260915'}}, {'ID_adapundi_finance_loans_revenue_simplified_repayday': {'DataSetId': 'f1c52058-5e6b-44fe-a442-a351bb777e40'}}, {'ID_adapundi_collection_weekly_re_payday_vintage': {'DataSetId': 'f47bc8bb-2805-4aa2-a5c7-a291682d6bc3'}}, {'happycash_daily_overdue_rate': {'DataSetId': 'f75dedb9-f50d-4f09-a812-43fa34742356'}}, {'happycash_daily_new_customer': {'DataSetId': 'f7a72fb8-d427-4f11-b5f9-57ebc6b22771'}}, {'credinex-交易': {'DataSetId': 'f8ec0230-6fbc-4848-bf34-5c79be87fc45'}}, {'Business Review': {'DataSetId': 'f9ae7250-9317-417c-a680-9306f7b992b8'}}, {'ID_dumarket_finance_ DokterDana_income': {'DataSetId': 'fa9f6156-914c-401c-bca0-f3f2f3a8ce6f'}}, {'ID_adapundi_marketing_message_trigger': {'DataSetId': 'faf0a5ac-d58c-4719-b862-995a748e9474'}}, {'ID_ada_coll._payday_vintage_rate(#)': {'DataSetId': 'fb000f37-32b7-4da0-89f4-9e3160b2139e'}}, {'ID_adapundi_telemarketing_handler_today_hour': {'DataSetId': 'fb60d7bc-a909-48d5-a129-7c11429ae17c'}}, {'ID_adapundi_marketing_register_basic_with_cost': {'DataSetId': 'fb79e81f-7040-42dc-9e5b-7fefbf479d0d'}}, {'ID_adapundi_marketing_register_basic_with_cost_channel_2': {'DataSetId': 'fc66d960-3c8a-4cbe-b6cf-dc1207b086a6'}}, {'ID_adapundi_risk_level_conversion_old': {'DataSetId': 'fdfc73a7-14fe-4cac-acec-13b673416ca7'}}, {'ID_dumarket_product_situation': {'DataSetId': 'fe3d4508-3f00-4254-9406-fe6d67602224'}}, {'happycash_daily_finance_total': {'DataSetId': 'fe55f079-b266-4d54-a3c6-0a499982eac1'}}, {'ID_adapundi_finance_kkk': {'DataSetId': 'feebf817-9e92-4a89-897d-02100a7c0fab'}}]

def list_data_sets():
    datasetList = []
    nexttoken = None
    while nexttoken == None or nexttoken !="":
        ls = []
        if nexttoken == None:
            response = client.list_data_sets(AwsAccountId='855696220043', MaxResults=100)
            print(response)
            ls = list(map(lambda x: {x["Name"]: {"DataSetId": x["DataSetId"]}}, response["DataSetSummaries"]))
            nexttoken = response["NextToken"] if response.get("NextToken", False) else ""
            datasetList.extend(ls)
        else:
            response = client.list_data_sets(AwsAccountId='855696220043', NextToken=nexttoken, MaxResults=100)
            ls = list(map(lambda x: {x["Name"]: {"DataSetId": x["DataSetId"]}}, response["DataSetSummaries"]))
            datasetList.extend(ls)
            print(response)
            nexttoken = response["NextToken"] if response.get("NextToken", False) else ""
#     print(datasetList)
    return datasetList;
# datasetList=list_data_sets()

for dataset in datasetList:
    for datasetNm in dataset:
        DataSetId=dataset[datasetNm]["DataSetId"]
        response = client.describe_data_set(
            AwsAccountId='855696220043',
            DataSetId=DataSetId
        )
        print(response)
        print(response['DataSet']['LogicalTableMap'])
        sourceId = [i for i in response['DataSet']['PhysicalTableMap']][0]
        if sourceId=='s3PhysicalTable':
            continue
        tableName=response['DataSet']['Name']
        if response['DataSet']['PhysicalTableMap'][sourceId].get("CustomSql") is None:
            continue
        sql=response['DataSet']['PhysicalTableMap'][sourceId]['CustomSql']['SqlQuery']
        # f=open("/sql/"+tableName+'.txt',"a")
        # f.write(sql) # f为文件对象
        matchObj = re.findall(pattern, tableName)
        key='private/athenaSQl/'+tableName+'.txt'
        Bucket='floatingshelf114234-hanpeng'
        s3.put_object(Body=sql, Bucket=Bucket,Key=key, ACL='public-read')
        tableconf={
            "id": {"S":tableName},
            "tableNm":{"S":tableName},
            "tbtype":{"S":matchObj[0].upper() if len(matchObj)>0 else "OTHER"},
            "executecycle":{"S":"DAILY" if len(matchObj)>0 else "OTHER"},
            "sqlbucket":{"S":Bucket},
            "sqlpath":{"S":key},
            "sqlexecid":{"S":""},
            "sqlexecdate":{"S":""},
            "resultbucket":{"S":""},
            "resultpath": {"S":""},
            "tablecreatedDate":{"S":""},
            "sqlcreatedDate":{"S":datetime.now().strftime('%Y-%m-%d %H:%M:%S')},
            "sqlupdateDate":{"S":datetime.now().strftime('%Y-%m-%d %H:%M:%S')},
            "createdAt":{"S":datetime.now().strftime('%Y-%m-%dT%H:%M:%SZ')},
            "updatedAt":{"S":datetime.now().strftime('%Y-%m-%dT%H:%M:%SZ')}
        }
        response = dynamodb.put_item(
            TableName='AnalysisReportSql-v6q6okep3bebnkt4bszyldyyie-hanpeng',
            Item=tableconf
        )

VBox()

FloatProgress(value=0.0, bar_style='info', description='Progress:', layout=Layout(height='25px', width='50%'),…

{'ResponseMetadata': {'RequestId': '2675ac42-b5fc-42e9-b869-901d43d05d30', 'HTTPStatusCode': 200, 'HTTPHeaders': {'date': 'Tue, 30 Mar 2021 11:02:12 GMT', 'content-type': 'application/json', 'content-length': '10799', 'connection': 'keep-alive', 'x-amzn-requestid': '2675ac42-b5fc-42e9-b869-901d43d05d30'}, 'RetryAttempts': 0}, 'Status': 200, 'DataSet': {'Arn': 'arn:aws:quicksight:ap-southeast-1:855696220043:dataset/01347efb-eee0-4fcf-bb53-b47aacf83c7c', 'DataSetId': '01347efb-eee0-4fcf-bb53-b47aacf83c7c', 'Name': 'ID_adapundi_marketing_auto_task_total', 'CreatedTime': datetime.datetime(2020, 8, 3, 7, 38, 6, 839000, tzinfo=tzlocal()), 'LastUpdatedTime': datetime.datetime(2021, 3, 30, 1, 3, 24, 681000, tzinfo=tzlocal()), 'PhysicalTableMap': {'bda13629-1600-4597-8333-4426f17130f9': {'CustomSql': {'DataSourceArn': 'arn:aws:quicksight:ap-southeast-1:855696220043:datasource/fa35a4ae-150d-4473-8894-22eed8493970', 'Name': 'ID_adapundi_marketing_auto_task_total', 'SqlQuery': 'with loan as\t\t\n(\t\t\n  SELECT app.customer_id,count(distinct app.id) as apply,\t\t\n  count(distinct if(log.new_status in (\'AUTHORIZATION\',\'BIND_CARD\',\'ISSUING\',\'READY_TO_ISSUE\',\'CURRENT\' ,\'PAID_OFF\', \'GRACE_PERIOD\', \'OVERDUE\'),app.id,null)) as AUTHORIZATION,\t\t\n  count(distinct if(log.new_status in (\'BIND_CARD\',\'ISSUING\',\'READY_TO_ISSUE\',\'CURRENT\' ,\'PAID_OFF\', \'GRACE_PERIOD\', \'OVERDUE\'),app.id,null)) as withdrawn,\t\t\n  count(distinct if(app.status in (\'CURRENT\' ,\'PAID_OFF\', \'GRACE_PERIOD\', \'OVERDUE\'),app.id,null)) as issue,\t\t\n  sum(if(log.new_status  = \'CURRENT\',app.amount,0)) as issue_amount\t\t\n  FROM "banda-etl-s3"."t_loan_app" app\n  left join "banda-etl-s3"."t_loan_app_status_log" log\n  on app.id = log.loan_app_id\t\t\n  where date(app.create_time + interval \'7\' hour) >= date \'2019-08-01\' and app.loan_type in (\'PAYDAY\' ,\'RE_PAYDAY\')\n  group by app.customer_id\t\t\n),\t\t\nwa as\t\t\n(\t\t\n  SELECT cu.id,count(me.id) as wa\t\t\n  FROM "notification_etl_s3"."t_message" me\t\t\n  left join  "notification_etl_s3"."t_trigger" a\t\t\n  on me.trigger_id = a.id\t\t\n  left join "notification_etl_s3"."t_product_department" b \t\t\n  on a.type_id = b.id\t\t\n  left join "banda-etl-s3"."t_customer" cu\n  on me.send_to = cu.mobile\t\t\n  where a.product_id = 0 and b.id in (1,2) and me.type = \'WHATS_APPS\' and me.status = \'SUCCESS\'\t\t\n  group by cu.id \t\t\n),\t\t\ncall as\t\t\n(\t\t\n  SELECT pool.customer_id,count(call.id) as call,count(if(call.status = \'ANSWERED\',call.id,null)) as answer\t\t\n  FROM "telemarket_etl_s3"."t_task_pool" pool\t\t\n  left join "telemarket_etl_s3"."t_callcenter_call_journaling" call\t\t\n  on pool.id = call.case_id\t\t\n  where call.id>0\t\t\n  group by pool.customer_id\t\t\n),\t\t\ncoupon as \t\t\n(\t\t\n  select cast(customer_id as bigint) as customer_id,count(if(coupon_type = 0,id,null)) as withdraw_coupon_count,\t\t\n  count(if(coupon_type = 1,id,null)) as interst_free_coupon_count,\t\t\n  sum(if(coupon_type = 1,cast(json_extract_scalar(structure,\'$.amount\') as decimal),0)) as interst_free_coupon_amount,\n  sum(if(coupon_type = 1 and \n         cast(loan_id as bigint) in (select id from "banda-etl-s3"."t_loan_app" \n                                     where status = \'PAID_OFF\'),\n         cast(json_extract_scalar(structure,\'$.amount\') as decimal),0)) as interst_free_coupon_amount_use\n  from "coupon_etl_s3"."t_coupon_record"\t\t\n  where product_id = 1 and status = 2\tand  \n  cast(loan_id as bigint) in (select id from "banda-etl-s3"."t_loan_app" where status in (\'CURRENT\' ,\'PAID_OFF\', \'GRACE_PERIOD\', \'OVERDUE\'))\n  group by cast(customer_id as bigint)\t\t\n),\t\t\nsms as\t\t\n(\t\t\n  SELECT cu.id,count(if(a.id = 41 and me.type= \'SMS\',me.id,null)) as sms_verification_code,\t\t\n  \t\t count(if(a.id = 41 and me.type= \'SMS_VOICE\',me.id,null)) as sms_voice_verification_code,\n  count(if(a.id != 41 and a.type_id = 2,me.id,null)) as sms_notification_code,\t\t\n  count(if(a.id != 41 and a.type_id = 1,me.id,null)) as sms_marketing_code\t\t\n  FROM "notification_etl_s3"."t_message" me\t\t\n  left join  "notification_etl_s3"."t_trigger" a\t\t\n  on me.trigger_id = a.id\t\t\n  left join "notification_etl_s3"."t_product_department" b \t\t\n  on a.type_id = b.id\t\t\n  left join "banda-etl-s3"."t_customer" cu\n  on me.send_to = cu.mobile\t\t\n  where a.product_id = 0 and b.id in (1,2) and me.type in (\'SMS\') and me.status = \'SUCCESS\'\t\t\n  group by cu.id \t\t\n),\t\t\nvoice as\t\t\n(\t\t\n  select cu.id,count(code.id) as voice\t\t\n  from "banda-etl-s3"."t_code" code\n  left join "banda-etl-s3"."t_customer" cu\n  on code.send_to = cu.mobile\t\t\n  where code.send_type = \'VOICE\' \t\t\n  group by cu.id\t\t\n)\t\t\n \t\t\n\t\t\nselect date(cu.create_time+ interval \'7\' hour) as date,\t\t\ncount(cu.id) as register,count(loan.customer_id) as apply,\t\t\ncount(if(loan.AUTHORIZATION>0,loan.customer_id,null)) as authorization,\t\t\ncount(if(loan.withdrawn>0,loan.customer_id,null)) as withdrawn,\t\t\ncount(if(loan.issue>0,loan.customer_id,null)) as issue,\t\t\ncoalesce(sum(if(loan.issue>0,loan.issue,0)),0) as issue_count,\t\t\ncoalesce(1.0*sum(if(loan.issue>0,loan.issue_amount,0))/14000,0)  as issue_amount,\t\t\ncoalesce(sum(wa.wa),0) as wa_count,\t\t\n1.0*count(if(wa.wa>0,wa.id,null))/count(cu.id) as register_wa_rate,\t\t\ncoalesce(sum(call.call),0) as call_count,\t\t\n1.0*count(if(call.answer>0,call.customer_id,null))/count(cu.id) as register_call_answer_rate,\t\t\ncoalesce(sum(withdraw_coupon_count),0) as withdraw_coupon_count,\t\t\ncoalesce(sum(interst_free_coupon_count),0) as interst_free_coupon_count,\t\t\ncoalesce(1.0*sum(interst_free_coupon_amount)/14000,0) as interst_free_coupon_amount,\ncoalesce(1.0*sum(interst_free_coupon_amount_use)/14000,0) as interst_free_coupon_amount_use,\ncoalesce(sum(sms_verification_code),0) as sms_verification_code,\t\t\ncoalesce(sum(voice),0) as voice_verification_code,\t\t\ncoalesce(sum(sms_notification_code),0) as sms_notification_code,\t\t\ncoalesce(sum(sms_marketing_code),0) as sms_marketing_code,\t\t\n(0.0520*coalesce(sum(call.call),0)) + (0.0250*coalesce(sum(sms_verification_code),0))+\t\t\n(0.0100*coalesce(sum(voice),0)) + (0.0077*coalesce(sum(wa.wa),0))+\t\t\n(0.0050*(coalesce(sum(sms_notification_code),0)+coalesce(sum(sms_marketing_code),0))) as cost,\t\t\n\t\t\ncase when coalesce(sum(if(loan.issue>0,loan.issue,0)),0) > 0 then ((0.0520*coalesce(sum(call.call),0)) + (0.0250*coalesce(sum(sms_verification_code),0))+\t\t\n(0.0100*coalesce(sum(voice),0)) + (0.0077*coalesce(sum(wa.wa),0))+\t\t\n(0.0050*(coalesce(sum(sms_notification_code),0)+coalesce(sum(sms_marketing_code),0))))/coalesce(sum(if(loan.issue>0,loan.issue,0)),0)\t\t\nelse 0 end  as cac,\t\t\n\t\t\ncase when coalesce(1.0*sum(if(loan.issue>0,loan.issue_amount,0))/14000,0) > 0 then ((0.0520*coalesce(sum(call.call),0)) + (0.0250*coalesce(sum(sms_verification_code),0))+\t\t\n(0.0100*coalesce(sum(voice),0)) + (0.0077*coalesce(sum(wa.wa),0))+\t\t\n(0.0050*(coalesce(sum(sms_notification_code),0)+coalesce(sum(sms_marketing_code),0))))/coalesce(1.0*sum(if(loan.issue>0,loan.issue_amount,0))/14000,0)\t\t\nelse 0 end  as cpa\t\t\n\t\t\nfrom "banda-etl-s3".t_customer cu\nleft join loan\t\t\non cu.id = loan.customer_id\t\t\nleft join wa\t\t\non cu.id = wa.id\t\t\nleft join coupon\t\t\non cu.id = coupon.customer_id\t\t\nleft join sms\t\t\non cu.id = sms.id\t\t\nleft join call\t\t\non cu.id = call.customer_id\t\t\nleft join voice\t\t\non cu.id = voice.id\t\t\nwhere date(cu.create_time+ interval \'7\' hour) >= date \'2019-08-01\'\ngroup by date(cu.create_time+ interval \'7\' hour)\t\t\norder by date(cu.create_time+ interval \'7\' hour) desc', 'Columns': [{'Name': 'date', 'Type': 'DATETIME'}, {'Name': 'register', 'Type': 'INTEGER'}, {'Name': 'apply', 'Type': 'INTEGER'}, {'Name': 'authorization', 'Type': 'INTEGER'}, {'Name': 'withdrawn', 'Type': 'INTEGER'}, {'Name': 'issue', 'Type': 'INTEGER'}, {'Name': 'issue_count', 'Type': 'INTEGER'}, {'Name': 'issue_amount', 'Type': 'DECIMAL'}, {'Name': 'wa_count', 'Type': 'INTEGER'}, {'Name': 'register_wa_rate', 'Type': 'DECIMAL'}, {'Name': 'call_count', 'Type': 'INTEGER'}, {'Name': 'register_call_answer_rate', 'Type': 'DECIMAL'}, {'Name': 'withdraw_coupon_count', 'Type': 'INTEGER'}, {'Name': 'interst_free_coupon_count', 'Type': 'INTEGER'}, {'Name': 'interst_free_coupon_amount', 'Type': 'DECIMAL'}, {'Name': 'interst_free_coupon_amount_use', 'Type': 'DECIMAL'}, {'Name': 'sms_verification_code', 'Type': 'INTEGER'}, {'Name': 'voice_verification_code', 'Type': 'INTEGER'}, {'Name': 'sms_notification_code', 'Type': 'INTEGER'}, {'Name': 'sms_marketing_code', 'Type': 'INTEGER'}, {'Name': 'cost', 'Type': 'DECIMAL'}, {'Name': 'cac', 'Type': 'DECIMAL'}, {'Name': 'cpa', 'Type': 'DECIMAL'}]}}}, 'LogicalTableMap': {'bda13629-1600-4597-8333-4426f17130f9': {'Alias': 'ID_adapundi_marketing_auto_task_total', 'DataTransforms': [{'ProjectOperation': {'ProjectedColumns': ['date', 'register', 'apply', 'authorization', 'withdrawn', 'issue', 'issue_count', 'issue_amount', 'wa_count', 'register_wa_rate', 'call_count', 'register_call_answer_rate', 'withdraw_coupon_count', 'interst_free_coupon_count', 'interst_free_coupon_amount', 'interst_free_coupon_amount_use', 'sms_verification_code', 'voice_verification_code', 'sms_notification_code', 'sms_marketing_code', 'cost', 'cac', 'cpa']}}], 'Source': {'PhysicalTableId': 'bda13629-1600-4597-8333-4426f17130f9'}}}, 'OutputColumns': [{'Name': 'date', 'Type': 'DATETIME'}, {'Name': 'register', 'Type': 'INTEGER'}, {'Name': 'apply', 'Type': 'INTEGER'}, {'Name': 'authorization', 'Type': 'INTEGER'}, {'Name': 'withdrawn', 'Type': 'INTEGER'}, {'Name': 'issue', 'Type': 'INTEGER'}, {'Name': 'issue_count', 'Type': 'INTEGER'}, {'Name': 'issue_amount', 'Type': 'DECIMAL'}, {'Name': 'wa_count', 'Type': 'INTEGER'}, {'Name': 'register_wa_rate', 'Type': 'DECIMAL'}, {'Name': 'call_count', 'Type': 'INTEGER'}, {'Name': 'register_call_answer_rate', 'Type': 'DECIMAL'}, {'Name': 'withdraw_coupon_count', 'Type': 'INTEGER'}, {'Name': 'interst_free_coupon_count', 'Type': 'INTEGER'}, {'Name': 'interst_free_coupon_amount', 'Type': 'DECIMAL'}, {'Name': 'interst_free_coupon_amount_use', 'Type': 'DECIMAL'}, {'Name': 'sms_verification_code', 'Type': 'INTEGER'}, {'Name': 'voice_verification_code', 'Type': 'INTEGER'}, {'Name': 'sms_notification_code', 'Type': 'INTEGER'}, {'Name': 'sms_marketing_code', 'Type': 'INTEGER'}, {'Name': 'cost', 'Type': 'DECIMAL'}, {'Name': 'cac', 'Type': 'DECIMAL'}, {'Name': 'cpa', 'Type': 'DECIMAL'}], 'ImportMode': 'SPICE', 'ConsumedSpiceCapacityInBytes': 167808}, 'RequestId': '2675ac42-b5fc-42e9-b869-901d43d05d30'}
{'bda13629-1600-4597-8333-4426f17130f9': {'Alias': 'ID_adapundi_marketing_auto_task_total', 'DataTransforms': [{'ProjectOperation': {'ProjectedColumns': ['date', 'register', 'apply', 'authorization', 'withdrawn', 'issue', 'issue_count', 'issue_amount', 'wa_count', 'register_wa_rate', 'call_count', 'register_call_answer_rate', 'withdraw_coupon_count', 'interst_free_coupon_count', 'interst_free_coupon_amount', 'interst_free_coupon_amount_use', 'sms_verification_code', 'voice_verification_code', 'sms_notification_code', 'sms_marketing_code', 'cost', 'cac', 'cpa']}}], 'Source': {'PhysicalTableId': 'bda13629-1600-4597-8333-4426f17130f9'}}}
{'ResponseMetadata': {'RequestId': 'PPWY4SPDS6RTHCBD', 'HostId': '4TWuHp6F2bQPuAx6GOo6mGNHMMtPHMTbImumNVFXEOzByHHNVNtJ2SgBatOMifNHE9DmPTDlzNg=', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amz-id-2': '4TWuHp6F2bQPuAx6GOo6mGNHMMtPHMTbImumNVFXEOzByHHNVNtJ2SgBatOMifNHE9DmPTDlzNg=', 'x-amz-request-id': 'PPWY4SPDS6RTHCBD', 'date': 'Tue, 30 Mar 2021 11:02:13 GMT', 'etag': '"1ff0fcfcac7850ce0b5aff16d88edf0a"', 'content-length': '0', 'server': 'AmazonS3'}, 'RetryAttempts': 1}, 'ETag': '"1ff0fcfcac7850ce0b5aff16d88edf0a"'}
{'ResponseMetadata': {'RequestId': 'b4a9fced-29f5-48ce-bdab-83398e6c0b2b', 'HTTPStatusCode': 200, 'HTTPHeaders': {'date': 'Tue, 30 Mar 2021 11:02:13 GMT', 'content-type': 'application/json', 'content-length': '5611', 'connection': 'keep-alive', 'x-amzn-requestid': 'b4a9fced-29f5-48ce-bdab-83398e6c0b2b'}, 'RetryAttempts': 0}, 'Status': 200, 'DataSet': {'Arn': 'arn:aws:quicksight:ap-southeast-1:855696220043:dataset/02c90f3e-d17c-4cfe-b06b-4da4cb19371a', 'DataSetId': '02c90f3e-d17c-4cfe-b06b-4da4cb19371a', 'Name': 'ID_ada_collection_V-1', 'CreatedTime': datetime.datetime(2020, 1, 14, 10, 45, 55, 227000, tzinfo=tzlocal()), 'LastUpdatedTime': datetime.datetime(2021, 3, 29, 23, 59, 50, 179000, tzinfo=tzlocal()), 'PhysicalTableMap': {'cc069448-c513-43e6-b038-d6b9975bd9c2': {'CustomSql': {'DataSourceArn': 'arn:aws:quicksight:ap-southeast-1:855696220043:datasource/12d7c270-373b-4eb6-b6b6-ded01b512047', 'Name': 'ID_adapundi_collection_vintage-1_rate', 'SqlQuery': 'SELECT t3.date2 AS view_date\n,t3.all_due_count,t3.payday_due_count,t3.re_payday_due_count,t3.rollover_due_count,t3.all_overdue_count,t3.payday_overdue_count,t3.re_payday_overdue_count,t3.rollover_overdue_count\nFROM (SELECT t2.date2,sum(t1.due_count)AS all_due_count\n  ,SUM(CASE WHEN t1.loan_type=\'PAYDAY\'THEN t1.due_count ELSE 0 END )AS payday_due_count\n  ,SUM(CASE WHEN t1.loan_type=\'RE_PAYDAY\'THEN t1.due_count ELSE 0 END )AS re_payday_due_count\n  ,SUM(CASE WHEN t1.loan_type=\'ROLLOVER\'THEN t1.due_count ELSE 0 END )AS rollover_due_count\n  ,sum(t2.overdue_count)AS all_overdue_count\n  ,SUM(CASE WHEN t1.loan_type=\'PAYDAY\'THEN t2.overdue_count ELSE 0 END )AS payday_overdue_count\n  ,SUM(CASE WHEN t1.loan_type=\'RE_PAYDAY\'THEN t2.overdue_count ELSE 0 END )AS re_payday_overdue_count\n  ,SUM(CASE WHEN t1.loan_type=\'ROLLOVER\'THEN t2.overdue_count ELSE 0 END )AS rollover_overdue_count\nFROM (SELECT date(lpay.due_date+interval\'7\' hour)AS date1,date(lpay.due_date+interval\'-1\' day +interval \'7\' hour) as date2,app.loan_type,count(DISTINCT APP.id)AS due_count\nFROM  "banda-etl-s3".t_loan_app app\nLEFT JOIN "banda-etl-s3".t_lpay lpay ON lpay.loan_app_id=app.id\nWHERE app.status IN (\'CURRENT\',\'GRACE_PERIOD\',\'OVERDUE\',\'PAID_OFF\')\nAND date_diff(\'day\',date(lpay.due_date+interval\'-1\' day +interval \'7\' hour),date(now()+INTERVAL \'7\' hour))>=0\nAND date_diff(\'day\',date(lpay.due_date+interval\'-1\' day +interval \'7\' hour),date(now()+INTERVAL \'-2\' month +INTERVAL \'7\' hour))< day(now()+interval\'7\' hour)    \nAND day(lpay.due_date+interval\'-1\' day +interval \'7\' hour)-day(now()+INTERVAL\'7\' hour)<=0\nGROUP BY date(lpay.due_date+interval\'7\' hour),date(lpay.due_date+interval\'-1\' day +interval \'7\' hour),app.loan_type\n     )t1\nLEFT JOIN\n(SELECT date(lpay.due_date+interval\'7\' hour)AS date1,date(lpay.due_date+interval\'-1\' day +interval \'7\' hour) as date2,app.loan_type,count(DISTINCT APP.id)AS overdue_count\nFROM "banda-etl-s3".t_loan_app app\nLEFT JOIN "banda-etl-s3".t_lpay lpay ON lpay.loan_app_id=app.id\nLEFT JOIN (SELECT app2.id  FROM "banda-etl-s3".t_loan_app App2\n           LEFT JOIN  "banda-etl-s3".t_lpay lpay2 ON lpay2.loan_app_id=app2.id\n           LEFT JOIN  "banda-etl-s3".t_loan_app_status_log lg ON lg.loan_app_id=app2.id\n           WHERE app2.status IN (\'CURRENT\',\'GRACE_PERIOD\',\'OVERDUE\',\'PAID_OFF\')\n           AND lg.new_status=\'PAID_OFF\'\n           AND  date_diff(\'day\',date(lpay2.due_date+interval \'7\' hour),date(lg.create_time+INTERVAL \'7\' hour))<-1)t4 on t4.id=app.id\nWHERE app.status IN (\'CURRENT\',\'GRACE_PERIOD\',\'OVERDUE\',\'PAID_OFF\')\nand t4.id IS NULL\nand date_diff(\'day\',date(lpay.due_date+interval\'-1\' day +interval \'7\' hour),date(now()+INTERVAL \'7\' hour))>=0\nand date_diff(\'day\',date(lpay.due_date+interval\'-1\' day +interval \'7\' hour),date(now()+INTERVAL \'-2\' month +INTERVAL \'7\' hour))< day(now()+interval\'7\' hour)   \nAND day(lpay.due_date+interval\'-1\' day +interval \'7\' hour)-day(now()+INTERVAL\'7\' hour)<=0\nGROUP BY date(lpay.due_date+interval\'7\' hour),date(lpay.due_date+interval\'-1\' day +interval \'7\' hour),app.loan_type)t2 ON t2.date1=t1.date1 AND t2.loan_type=t1.loan_type AND t2.date2=t1.date2\nGROUP BY t2.date2)t3', 'Columns': [{'Name': 'view_date', 'Type': 'DATETIME'}, {'Name': 'all_due_count', 'Type': 'INTEGER'}, {'Name': 'payday_due_count', 'Type': 'INTEGER'}, {'Name': 're_payday_due_count', 'Type': 'INTEGER'}, {'Name': 'rollover_due_count', 'Type': 'INTEGER'}, {'Name': 'all_overdue_count', 'Type': 'INTEGER'}, {'Name': 'payday_overdue_count', 'Type': 'INTEGER'}, {'Name': 're_payday_overdue_count', 'Type': 'INTEGER'}, {'Name': 'rollover_overdue_count', 'Type': 'INTEGER'}]}}}, 'LogicalTableMap': {'cc069448-c513-43e6-b038-d6b9975bd9c2': {'Alias': 'ID_adapundi_collection_vintage-1_rate', 'DataTransforms': [{'ProjectOperation': {'ProjectedColumns': ['view_date', 'all_due_count', 'payday_due_count', 're_payday_due_count', 'rollover_due_count', 'all_overdue_count', 'payday_overdue_count', 're_payday_overdue_count', 'rollover_overdue_count']}}], 'Source': {'PhysicalTableId': 'cc069448-c513-43e6-b038-d6b9975bd9c2'}}}, 'OutputColumns': [{'Name': 'view_date', 'Type': 'DATETIME'}, {'Name': 'all_due_count', 'Type': 'INTEGER'}, {'Name': 'payday_due_count', 'Type': 'INTEGER'}, {'Name': 're_payday_due_count', 'Type': 'INTEGER'}, {'Name': 'rollover_due_count', 'Type': 'INTEGER'}, {'Name': 'all_overdue_count', 'Type': 'INTEGER'}, {'Name': 'payday_overdue_count', 'Type': 'INTEGER'}, {'Name': 're_payday_overdue_count', 'Type': 'INTEGER'}, {'Name': 'rollover_overdue_count', 'Type': 'INTEGER'}], 'ImportMode': 'SPICE', 'ConsumedSpiceCapacityInBytes': 9504}, 'RequestId': 'b4a9fced-29f5-48ce-bdab-83398e6c0b2b'}
{'cc069448-c513-43e6-b038-d6b9975bd9c2': {'Alias': 'ID_adapundi_collection_vintage-1_rate', 'DataTransforms': [{'ProjectOperation': {'ProjectedColumns': ['view_date', 'all_due_count', 'payday_due_count', 're_payday_due_count', 'rollover_due_count', 'all_overdue_count', 'payday_overdue_count', 're_payday_overdue_count', 'rollover_overdue_count']}}], 'Source': {'PhysicalTableId': 'cc069448-c513-43e6-b038-d6b9975bd9c2'}}}
{'ResponseMetadata': {'RequestId': '8M4A7V163GJPFKYG', 'HostId': 'RmnpDxE/+DwUDKErwib9apIXG0h1VWgmzEpBXkvfrLx1EsXdR3RY8PwzZ7t+sot5TFNr/QYGwko=', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amz-id-2': 'RmnpDxE/+DwUDKErwib9apIXG0h1VWgmzEpBXkvfrLx1EsXdR3RY8PwzZ7t+sot5TFNr/QYGwko=', 'x-amz-request-id': '8M4A7V163GJPFKYG', 'date': 'Tue, 30 Mar 2021 11:02:14 GMT', 'etag': '"b5949838e7d52cfec4191aa028b20030"', 'content-length': '0', 'server': 'AmazonS3'}, 'RetryAttempts': 0}, 'ETag': '"b5949838e7d52cfec4191aa028b20030"'}

In [5]:
from datetime import datetime
print(datetime.now().strftime('%Y-%m-%dT%H:%M:%SZ'))

VBox()

FloatProgress(value=0.0, bar_style='info', description='Progress:', layout=Layout(height='25px', width='50%'),…

2021-03-22T03:06:19Z